services:
  # WG-EASY - WireGuard Easy
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
      - t2_proxy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - $DOCKERDIR/appdata/wireguard:/etc/wireguard
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=$SERVER_IP
      - PASSWORD=$WGEASY_PASSWORD
      # Optional:
      # - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.20.x
      - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=0.0.0.0/0
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt