services:
  # Uptime Kuma
  uptime-kuma-local:
    image: ghcr.io/louislam/uptime-kuma:2.0.0-beta.1
    container_name: uptime-kuma-local
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      dockervlan:
        ipv4_address: 10.1.140.252 # You can specify a static IP
    # ports:
    #   - "3001:3001"
    volumes:
      - $DOCKERDIR/docker-hub/uptime-kuma:/app/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.uptime-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptime-rtr.rule=Host(`uptime.$DOMAINNAME_INTERNAL`) || Host(`status.${DOMAINNAME_INTERNAL}`)"
      - "traefik.http.routers.uptime-rtr.tls=true"
      # Middlewares
      # - "traefik.http.routers.uptime-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.uptime-rtr.service=uptime-svc"
      - "traefik.http.services.uptime-svc.loadbalancer.server.port=3001"